---

- name: ensure pciutils is installed
  yum:
    name: pciutils
    state: present

- name: get pci slot
  shell: lspci -mm | grep "{{ pci_device_key_name }}" | cut -d " " -f 1
  register: pci_slot

- block:
    - name: find vendor_device
      shell: lspci -kn -s "{{ item }}" | head -1 | cut -d" " -f 3 | tr -d '[:space:]'
      register: pci_vendor_device
      loop: "{{ pci_slot.stdout_lines }}"

    - name: find module
      shell: lspci -vkmmn -s "{{ item }}" | grep "^Module:" | cut -d":" -f 2 | tr -d '[:space:]'
      register: pci_module
      loop: "{{ pci_slot.stdout_lines }}"
  when: pci_slot.stdout | length > 0

- include_tasks: update_kernel.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: unbind_gpu.yml
  when: unbind_gpu|bool

- name: ensure playbook is create for local execution
  template:
    src: playbooks/enable_gpu_passthrough.yml
    dest: /root/enable_gpu_passthrough.yml
  vars:
    _pci_device_key_name: "{{ pci_device_key_name }}"
    _detach_gpu_from_host: "{{ detach_gpu_from_host | bool }}"

- name: flush handlers
  meta: flush_handlers