---

- name: add consoleblank to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*\ consoleblank)\"[^\"]+)(\".*)'
    line: '\1 {{ console_arg }}\2'
  when: set_consoleblank|bool
  notify: reboot system

- name: add pci-stub.ids to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*vfio-pci.ids)\"[^\"]+)(\".*)'
    line: '\1 {{ vfio_pci_ids_arg }}\2'
  when: pci_vendor_device is defined
  notify: reboot system

- name: add rdblacklist to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*rd.driver.blacklist)\"[^\"]+)(\".*)'
    line: '\1 {{ blacklists_arg }}\2'
  when: pci_module is defined
  notify: reboot system

- name: add iommu=pt to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*\ iommu)\"[^\"]+)(\".*)'
    line: '\1 iommu=pt\2'
  notify: reboot system

- name: add {{ cpu_type }}_iommu to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*{{ cpu_type }}_iommu)\"[^\"]+)(\".*)'
    line: '\1 {{ cpu_type }}_iommu=on\2'
  when: cpu_type is defined
  notify: reboot system

- name: add display arguments to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*\ {{ display_args }})\"[^\"]+)(\".*)'
    line: '\1 {{ display_args }}\2'
  when: detach_gpu_from_host|bool
  notify: reboot system

- include: rhel8_grub.yml

- include_tasks: detach_gpu.yml
  when: detach_gpu_from_host|bool