---

- name: add kernel parameters
  command: grubby --update-kernel ALL --args "{{ kernel_args }}"

- name: create vfio.conf file
  template:
    src: vfio.conf.j2
    dest: /etc/modprobe.d/vfio.conf
  when: pci_vendor_device is defined
  notify: reboot system

- name: create vfio-pci.conf file
  copy:
    dest: /etc/modules-load.d/vfio-pci.conf
    content: vfio-pci
  when: pci_vendor_device is defined
  notify: reboot system